apiVersion: v1
kind: Pod
metadata:
  name: one-waiting-one-non-zero-terminated-never
spec:
  containers:
    - name: non-zero-terminated
      image: busybox
      command: ["sh","-c","exit 1"]
    - name: waiting
      image: nginx2019:201
  restartPolicy: Never