apiVersion: v1
kind: Pod
metadata:
  name: two-waiting-never
spec:
  containers:
    - name: waiting-1
      image: nginx2019:201
    - name: waiting-2
      image: nginx2019:201
  restartPolicy: Never