apiVersion: v1
kind: Pod
metadata:
  name: one-zero-terminated-one-zero-terminated-on-failure
spec:
  containers:
    - name: zero-terminated
      image: busybox
      command: ["sh","-c","exit 0"]
    - name: non-zero-terminated
      image: busybox
      command: ["sh","-c","exit 1"]
  restartPolicy: OnFailure