apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-success-never
  labels:
    app: nginx-readiness-probe-success
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        httpGet:
          port: 80
  restartPolicy: Never