apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-failure-always
  labels:
    app: nginx-readiness-probe-failure
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        httpGet:
          port: 8080
  restartPolicy: Always