apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-success-never
spec:
  containers:
    - name: nginx
      image: nginx
      startupProbe:
        httpGet:
          port: 80
  restartPolicy: Never