apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-failure-never
spec:
  containers:
    - name: nginx
      image: nginx
      startupProbe:
        httpGet:
          port: 8080
  restartPolicy: Never