apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server-2
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: nginx
  template: 
    metadata:
      labels:
        app: nginx
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx