apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: development
  labels:
    app: nginx
    environment: development
    app.kubernetes.io/name: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/part-of: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
